### ISSUE TITLE
crypto order issue with error message "NAs introduced by coercion"

### ISSUE THREAD

**Issue by 3SMMZRjWgS** [JestonBlu/RobinHood#87] opened 2020-04-17 04:08 UTC
Hi JetsonBlu,

Really appreciate your work on this wrapper package. Been testing out buy/sell crypto orders function and kept experiencing the following error message:

```r
>   if (sell_quantity > 0) {
+     sell <- place_order_crypto(RH = RH, 
+                                symbol = ticker_rbh, 
+                                type = "market", 
+                                time_in_force = "gtc",
+                                price = sell_price,
+                                quantity = sell_quantity,
+                                side = "sell")
+     }

Warning message:
In api_orders_crypto(RH = RH, action = "order", currency_pair_id = currency_pair_id,  :
  NAs introduced by coercion
```

The very first buy order generated by this function tends to go through. The next one and the ones after will fail and trigger this error message. That happened to my initial test using CRAN 1.2.4. Then I removed 1.2.4 and installed Github 1.3.0. The problem disappeared on the first buy order, but then reappeared on subsequent buy orders. That was yesterday. I tried again today using 1.3.0 and all the buy orders went through for some reason. Tonight, I'm trying the sell order (see code above), and the error message came back. I removed Github 1.3.0 and installed 1.3.1 and the same error message came up when I try the above crypto sell order. 

FYI: I'm running Windows 10 Pro w. Microsoft R Open 3.5.3.

Would appreciate you taking a look at the problem when you get a chance.

Thank you very much!
J.

**Comment by JestonBlu** [comment] 2020-04-17 10:54
@3SMMZRjWgS thanks for letting me know, can you provide me with the values you tried to submit instead of the variable names so I can try and reproduce your error?

Did you run the exact same command twice? Meaning same values for all inputs? If not please provide the one that worked and the one that failed.

**Comment by 3SMMZRjWgS** [comment] 2020-04-17 19:59
@JestonBlu Thank you. 

I reran the same crypto sell order code this morning, and received the same error message. I listed the classes and values of each variables used. Below is the RStudio console output starting with the error message.

```
Warning message:
In api_orders_crypto(RH = RH, action = "order", currency_pair_id = currency_pair_id,  :
  NAs introduced by coercion
> class(sell_quantity)
[1] "numeric"
> sell_quantity
[1] 0.006534
> class(ticker_rbh)
[1] "character"
> ticker_rbh
[1] "ETH"
> class(sell_price)
[1] "numeric"
> sell_price
[1] 170.8732
> class(sell_quantity)
[1] "numeric"
> sell_quantity
[1] 0.006534
> class(sell)
[1] "list"
> sell
$price
[1] NA

$cumulative_quantity
numeric(0)

$quantity
numeric(0)

$rounded_executed_notional
numeric(0)

$created_at
POSIXct of length 0

$updated_at
POSIXct of length 0 

```
crypto buy order was experiencing the same error message before (on CRAN 1.2.4 and Github 1.3.0). But by rerunning the same crypto buy code under Github 1.3.1 yesterday and today worked fine. Below is the code that I used to test the crypto buy order that currently works.
```
buy <- place_order_crypto(RH = RH,
                              symbol = "ETH",
                              type = "limit",
                              time_in_force = "gtc",
                              price = 100,
                              quantity = 0.0065,
                              side = "buy")
```

**Comment by JestonBlu** [comment] 2020-04-17 20:42
Hmm im not sure... the last change to `api_orders_crypto()` was related to the (GH-83) commit a week ago. There was an API change on the RobinHood site that I had to update... i got a report that it affected the `get_orders_crypto()` function, but they both share the `api_orders_crypto()` function although they have different steps.

Are you saying now with the version on github thats working? Even when you run it multiple times? When you initially said that it works the first time but not the second my mind went to a specific package Im using to create a unique id which RH requires for crypto orders.

Please clarify if I am misunderstanding, otherwise this might have been fixed with that other commit. I left the issue open to see if anyone else reports it.

**Comment by 3SMMZRjWgS** [comment] 2020-04-17 21:03
@JestonBlu 
> Are you saying now with the version on github thats working? Even when you run it multiple times? 

Yes, it's working for the crypto buy orders only (single or multiple orders of the same values within the same login session) using GitHub 1.3.1.

> When you initially said that it works the first time but not the second my mind went to a specific package Im using to create a unique id which RH requires for crypto orders.

I suspected something similar to what you've described here when I was experiencing the "first order succeed and every next orders fail" symptom, especially when I tried it again the next day and experienced this repeated behavior. But that was CRAN 1.2.4 and Github 1.3.0. 

With Github 1.3.1, crypto buy orders seem to work without issues up to this point, but crypto sell orders experience the mentioned error message regardless if it's a first order, repeated orders within the same loging session, or on a new day. 

I will continue to do more digging as well while waiting to see if others experience the same issue.

**Comment by JestonBlu** [comment] 2020-04-17 21:34
Okay, thanks that is helpful, i will try to replicate with some sell orders... i have actually never tested sell orders so thanks.

**Comment by JestonBlu** [comment] 2020-04-18 02:18
Okay, i actually was able to reproduce you results, but I still did not get an error... however i did see that the command did not work on RH so it was effectively ignored. Your `class(sell)` returns a `list()` and when I tried it like that I got the same results. Can you try submitting it as a character value instead of a list? I think that will solve it. I was able to create 3 sell orders back to back with no issue. Let me know what you find.

**Comment by 3SMMZRjWgS** [comment] 2020-04-20 22:17
@JestonBlu 

Thank you for looking into this. Finally got around to it today myself. Taking cues from your suggested solution, I think I found the solution to my problem.

The NA coercion error was triggered by two things: 
1) if price input has more than 2 decimal places
2) if quantity input has more than 6 decimal places

With price and quantity meeting the above requirements, the crypto sell orders were going through without a problem. I'd imagine this is some sort of API restrictions imposed by Robinhood. I believe Robinhood's app has similar constraints. 

Just as a suggestion, it might be helpful to include those limitations in the package manual in future releases?

Again, thanks for helping! 
- J

**Comment by JestonBlu** [comment] 2020-04-21 03:13
Yeah, i see what you are saying. It works the same for the `place_order()` function as well. I can see that 4 decimals works for the crypto currency DOGE, but if you were to only put in 1 share then it would also fail, because I think you need to have a minimum purchase of 1 cent, which would make sense. When I put in an order totaling 1.5 cents, it took.  

In the documentation the qty does say that you should supply an integer, but it doesn't check for it. Also fractional shares will work for crypto so i need to remove that from the documentation. I also know that people can sign up for fractional shares trading on RH so I might not put in an integer check at this time, but I will makes some notes in help function. 

Thanks for determining the cause.

**Closed** 2020-04-21 03:27 UTC
