### ISSUE TITLE
get_order_history and get_positions

### ISSUE THREAD

**Issue by jgag0627** [JestonBlu/RobinHood#83] opened 2020-04-10 20:16 UTC
Hi

First, thank you for all your hard work!

I apologize if this is trivial. I have been looking for hours for a fix but I have been unsuccessful. 

1) get_positions: 

I have applied the RH$url.positions="https://api.robinhood.com/positions/"
workaround after experiencing the same issues as the first person to report an error. 

However, I am only getting my FIRST position and not the rest. Am I doing something wrong?

2) when using get_order_history(RH) I am getting the error:

 Error in `[.data.frame`(order_history, , c("created_at", "symbol", "side",  : 
 undefined columns selected

Again am I doing something wrong.

I am using R 3.5.2 on a mac that has Mojave Version 10.14.6. 

Thanks for your time

**Comment by JestonBlu** [comment] 2020-04-11 01:34
Thanks, did you try installing the GitHub package version after I pushed the fix yesterday? When I tested it I saw all of my equity positions. I'll do a comprehensive check of all of the functions tonight and address the issue you found. Thanks for reporting it, glad you are enjoying the package!

**Comment by JestonBlu** [comment] 2020-04-11 03:12
I was not able to see your issue with `get_order_history()`, but I did notice an issue with `get_order_history_crypto()` which I have fixed with this commit. Try installing the github version and letting me know if your issue still persists. Ill leave the issue open for now.

**Comment by jgag0627** [comment] 2020-04-11 12:58
Hi 

Thank you for your response. 

I did this today:

1) I removed the package by deleting it from /Library/Frameworks/R.framework/Resources/library

2) I installed it using
install.packages("RobinHood") and I got the same results.

3) I deleted it again and installed using

install_github("jestonblu/RobinHood")

I also got the same results as previously. 

I apologize pal, but when you say to install the github version, did you mean to install it in a different way than above? I have used git through the UNIX command line but new at R. 

Thanks!

**Comment by JestonBlu** [comment] 2020-04-11 13:35
Silly question, but Im assuming you were able to install the package from github without an error? Are you using RStudio? Thats really a great IDE for anyone using R, but especially for beginners. You can also easily install and uninstall packages without messing with your directories.

You might know this but just to make sure, if you want to install my development version which is currently slightly in front of CRAN then you need to have the package `devtools`

```r
# Development version
install.packages("devtools")
devtools::install_github("jestonblu/RobinHood")
```
Sorry if Im telling you stuff you already know, but once you verify the output of this then let me know what you are seeing and Ill jump back on it.

**Comment by jgag0627** [comment] 2020-04-11 14:03
Hey pal,

No apologies are necessary. I am the one worried I am wasting your time.

I am a novice compared to users like yourself but I have more
experience than real "newbies".

If you have the patience and energy I would love for you to not assume I
know anything because I often find that there are subtle nuances that I may
have missed in certain areas. I am much more interested in understanding
the nuts and bolts than just being a user.

That said, I should have been more clear. I did install everything exactly
as you stated. Thank you very much for taking the time to reiterate these
steps though. Sometimes, relatively 'low level' questions reveal that a
person took no time to work through the problem on their own (google)
before calling for someone to help. I spent half the day yesterday
researching your site and others before finally contacting you.

I am currently reading up on devtools. I am more than willing to try and
get this to work on my own so as not to waste your time. However, if you
are in a position to help that would be greatly appreciated. But, if not, I
completely understand.

Thanks for reply!

Jason

PS I have used RStudio in the past. I just did not like all the background
processes it was doing "on my behalf". It would drive me nuts sometimes.

**Comment by jgag0627** [comment] 2020-04-11 14:22
Hi Joseph,

Sorry, I thought get_positions was only showing my first option because I
thought that my entire portfolio were options. But it was showing the one
stock that I got free when joining Robinhood. I guess my options do not
show up under positions?

The order history still will not work. I am working on it.

I saw a discussion about option challenges on your site. I will read up.

Best,

Jason

**Comment by JestonBlu** [comment] 2020-04-11 21:34
Okay that makes sense. No i do not have options built in yet, I have a current branch that I am working on to add that. Likely will have the function name `get_positions_options()` similar to `get_positions_crypto()`. Options are a different API thats why they are not part of the function. I realize thats not too intuitive. 

Im considering changing the name of `get_positions()` to `get_positions_equity()` and then creating a new function from `get_positions()` that returns a list with all 3 positions calls. Probably a little ways away from implementing that though.

**Comment by jgag0627** [comment] 2020-04-12 00:29
Ok thanks pal!

**Comment by JestonBlu** [comment] 2020-04-12 00:31
Still curious about your order history issue, can you  share the output of the command?

**Comment by jgag0627** [comment] 2020-04-12 14:27
Thank you for taking the time.

I am using Rstudio per your suggestion and I am connected to your Github
account.

> get_order_history(RH)
Error in `[.data.frame`(order_history, , c("created_at", "symbol", "side",
 :
  undefined columns selected

I  looked at the codes of the files called but nothing stood out.

Best,

Jason

**Comment by JestonBlu** [comment] 2020-04-12 19:09
Okay, sorry im not able to reproduce your error, I will leave open for some time and see if anyone else has the same issue. Just added ACH tranfers, will likely push an update to CRAN sometime this week.

**Comment by jgag0627** [comment] 2020-04-14 14:05
Okay thank you very much!

**Closed** 2020-04-18 03:28 UTC
Labels: bug
