### ISSUE TITLE
New Limit order issue

### ISSUE THREAD

**Issue by ttrevisan18** [JestonBlu/RobinHood#71] opened 2019-10-02 13:55 UTC
Hey,

I think there is another issue with the limit order. Whenever I place a limit order I get the error below (NAs introduced by coercion). I did some troubleshooting and I think it has to do with the fact that it is requiring a stop price. Not all limit orders will have a stop price.  In the second screenshot below, there is a catch if where if type == market, you drop the stop price from the detail. Instead of doing this by type == market, maybe do it if is.null(stop_price). I cannot be certain this is where the bug is, but that is my guess.

![image](https://user-images.githubusercontent.com/45466366/66050180-b61fb900-e4fa-11e9-9ba2-723df799dc0a.png)

![image](https://user-images.githubusercontent.com/45466366/66050199-bfa92100-e4fa-11e9-91b8-a73ef2d13a03.png)

**Comment by JestonBlu** [comment] 2019-10-02 14:06
Okay, I think I know what the problem is. Ill fix tonight as well, thanks for the report.

**Comment by JestonBlu** [comment] 2019-10-03 02:10
Okay I think I have this fixed... the api is expecting the stop price field when the trigger = "stop" so I had it incorrectly doing it when type = "limit". I have pushed the fix to master. Will also keep this open till the weekend. Thanks for the help. Let me know if this is not resolved.
 
a95b6ea

**Comment by ttrevisan18** [comment] 2019-10-03 18:03
Looks to be fixed! Thanks for the quick response.

**Closed** 2019-10-06 13:30 UTC
Labels: bug
